'use strict';

const sinon = require('sinon');
const sandbox = sinon.createSandbox();
const { deployByRos } = require('../../lib/deploy/deploy-support-ros');
const client = require('../../lib/client');
const { setProcess } = require('../test-utils');
const assert = sandbox.assert;
const uuid = require('uuid');
const inquirer = require('inquirer');
const time = require('../../lib/time');

const changes = [
  {
    'ResourceChange': {
      'LogicalResourceId': 'RosDemo',
      'ResourceType': 'ALIYUN::FC::Service',
      'Action': 'Modify',
      'Details': [
        {
          'Target': {
            'Name': 'Description'
          }
        }
      ]
    }
  },
  {
    'ResourceChange': {
      'LogicalResourceId': 'RosDemoRosDemo',
      'ResourceType': 'ALIYUN::FC::Function',
      'Action': 'Modify',
      'Details': [
        {
          'Target': {
            'Name': 'Code'
          }
        },
        {
          'Target': {
            'Name': 'Timeout'
          }
        },
        {
          'Target': {
            'Name': 'Runtime'
          }
        }
      ]
    }
  }
];

const tpl = {};

const stackName = 'stackName';

const stackId = 'c2234cf3-40f1-440f-b634-51370180589a';

const listParams = {
  'RegionId': 'cn-beijing',
  'StackName.1': stackName,
  'PageSize': 50,
  'PageNumber': 1,
  'ShowNestedStack': false
};

const listEventsParams = {
  'StackId': stackId,
  'RegionId': 'cn-beijing',
  'PageSize': 50,
  'PageNumber': 1
};

const updateParams = {
  RegionId: 'cn-beijing',
  ChangeSetName: 'fun-random',
  StackId: stackId,
  ChangeSetType: 'UPDATE',
  Description: 'generated by Funcraft',
  TemplateBody: '{}',
  DisableRollback: false,
  TimeoutInMinutes: 10
};

const getStackParams = {
  'StackId': stackId,
  'RegionId': 'cn-beijing'
};


const getChangeSetParam = {
  'RegionId': 'cn-beijing',
  'ChangeSetId': 'changeSetId',
  'ShowTemplate': true
};

const execChangeSetParams = {
  RegionId: 'cn-beijing', 
  ChangeSetId: 'changeSetId'
};

const events = [
  { StatusReason: 'state changed',
    Status: 'UPDATE_COMPLETE',
    PhysicalResourceId: '9daa0176-02df-45b0-b0cc-22f66b6ff41f',
    LogicalResourceId: 'RosDemotest5',
    ResourceType: 'ALIYUN::ROS::Stack',
    StackId: 'db7d6ddc-b089-4a9f-baaf-79169d2eed6f',
    CreateTime: '2019-10-09T13:27:15',
    EventId: '5138c28b-08b2-4d6e-be6c-865f91779ebc',
    StackName: 'coco-superme'
  },
  { StatusReason: 'state changed',
    Status: 'UPDATE_COMPLETE',
    PhysicalResourceId: 'e2c71fd2-5bfb-4693-a4ef-728ecabc7613',
    LogicalResourceId: 'RosDemotest2',
    ResourceType: 'ALIYUN::FC::Function',
    StackId: 'db7d6ddc-b089-4a9f-baaf-79169d2eed6f',
    CreateTime: '2019-10-09T13:27:15',
    EventId: '2a6d975c-b1bc-40fe-a848-508a29269260',
    StackName: 'coco-superme'
  },
  { StatusReason: 'state changed',
    Status: 'UPDATE_COMPLETE',
    PhysicalResourceId: '27fe8d7d-657c-4e2c-8a02-7ef3e8f1fa0a',
    LogicalResourceId: 'RosDemotest1',
    ResourceType: 'ALIYUN::FC::Function',
    StackId: 'db7d6ddc-b089-4a9f-baaf-79169d2eed6f',
    CreateTime: '2019-10-09T13:27:15',
    EventId: '95519d25-3a4d-4321-96c3-c0b796d37789',
    StackName: 'coco-superme'
  },
  { StatusReason: 'state changed',
    Status: 'UPDATE_IN_PROGRESS',
    PhysicalResourceId: 'f5dcf959-07e7-4acc-8d45-9fab9ccac711',
    LogicalResourceId: 'RosDemotest3',
    ResourceType: 'ALIYUN::ROS::Stack',
    StackId: 'db7d6ddc-b089-4a9f-baaf-79169d2eed6f',
    CreateTime: '2019-10-09T13:27:15',
    EventId: '4bcd4524-f9d8-42c1-b097-aca101007e86',
    StackName: 'coco-superme'
  }
];

const eventsForStackProcess = [
  { StatusReason: 'state changed',
    Status: 'UPDATE_IN_PROGRESS',
    PhysicalResourceId: 'f5dcf959-07e7-4acc-8d45-9fab9ccac711',
    LogicalResourceId: 'RosDemotest3',
    ResourceType: 'ALIYUN::ROS::Stack',
    StackId: 'db7d6ddc-b089-4a9f-baaf-79169d2eed6f',
    CreateTime: '2019-10-09T13:27:15',
    EventId: '4bcd4524-f9d8-42c1-b097-aca101007e86',
    StackName: 'coco-superme'
  }
];

const resultsForStackProcess = {
  'PageNumber': 1,
  'TotalCount': 20,
  'PageSize': 50,
  'Events': eventsForStackProcess
};

const listEventsResults = {
  'PageNumber': 1,
  'TotalCount': 20,
  'PageSize': 50,
  'Events': events
};

describe('test deploy support ros', () => {
  const requestOption = {
    method: 'POST'
  };
  const answer = {
    'ok': true
  };

  let rosClient;
  let requestStub;
  let restoreProcess;
  beforeEach(() => {
    restoreProcess = setProcess({
      ACCOUNT_ID: 'testAccountId',
      ACCESS_KEY_ID: 'testKeyId',
      ACCESS_KEY_SECRET: 'testKeySecret',
      FC_ENDPOINT: 'test fc endpoint',
      REGION: 'cn-beijing'
    });

    requestStub = sandbox.stub();

    sandbox.stub(inquirer, 'prompt').resolves(answer);

    rosClient = {
      request: requestStub
    };

    sandbox.stub(time, 'sleep');
    sandbox.stub(client, 'getRosClient').resolves(rosClient);
    sandbox.stub(uuid, 'v4').returns('random');
  });

  afterEach(() => {
    restoreProcess();
    sandbox.restore();
  });

  it('fix ros deploy undefined bug', async () => {
    requestStub.withArgs('ListStacks', listParams, requestOption).resolves({
      'PageNumber': 1,
      'TotalCount': 3,
      'PageSize': 50,
      'Stacks': [
        {
          'StackId': stackId,
          'StackName': stackName
        }
      ]
    });

    requestStub.withArgs('CreateChangeSet', updateParams, requestOption).resolves({
      ChangeSetId: 'changeSetId'
    });

    requestStub.withArgs('GetStack', getStackParams).resolves({
      'Status': 'UPDATE_COMPLETE'
    });

    requestStub.withArgs('GetChangeSet', getChangeSetParam).resolves({
      'Status': 'COMPLETE',
      'Changes': changes
    });

    requestStub.withArgs('ExecuteChangeSet', execChangeSetParams, requestOption).resolves();
    requestStub.withArgs('ListStackEvents', listEventsParams, requestOption).onFirstCall().resolves(resultsForStackProcess);
    requestStub.withArgs('ListStackEvents', listEventsParams, requestOption).onSecondCall().resolves(listEventsResults);

    await deployByRos(stackName, tpl, true);

    assert.calledWith(requestStub.firstCall, 'ListStacks', listParams, requestOption);
    assert.calledWith(requestStub.secondCall, 'CreateChangeSet', updateParams, requestOption);
    assert.calledWith(requestStub.thirdCall, 'GetChangeSet', getChangeSetParam, requestOption);
    assert.calledWith(requestStub.lastCall, 'ListStackEvents', listEventsParams, requestOption);

    assert.callCount(requestStub, 6);
    assert.notCalled(inquirer.prompt);
  });

  it('test deploy by ros with assumeYes is true', async () => {
    requestStub.withArgs('ListStacks', listParams, requestOption).resolves({
      'PageNumber': 1,
      'TotalCount': 3,
      'PageSize': 50,
      'Stacks': [
        {
          'StackId': stackId,
          'StackName': stackName
        }
      ]
    });

    requestStub.withArgs('CreateChangeSet', updateParams, requestOption).resolves({
      ChangeSetId: 'changeSetId'
    });

    requestStub.withArgs('GetStack', getStackParams).resolves({
      'Status': 'UPDATE_COMPLETE'
    });

    requestStub.withArgs('GetChangeSet', getChangeSetParam).resolves({
      'Status': 'COMPLETE',
      'Changes': changes
    });

    requestStub.withArgs('ExecuteChangeSet', execChangeSetParams, requestOption).resolves();
    requestStub.withArgs('ListStackEvents', listEventsParams, requestOption).resolves(listEventsResults);

    await deployByRos(stackName, tpl, true);

    assert.calledWith(requestStub.firstCall, 'ListStacks', listParams, requestOption);
    assert.calledWith(requestStub.secondCall, 'CreateChangeSet', updateParams, requestOption);
    assert.calledWith(requestStub.thirdCall, 'GetChangeSet', getChangeSetParam, requestOption);
    assert.calledWith(requestStub.lastCall, 'ListStackEvents', listEventsParams, requestOption);

    assert.notCalled(inquirer.prompt);
  });

  // Causes travis mac nodejs9 and nodejs10 to fail
  it.skip('test deploy by ros with assumeYes is false', async () => {
    requestStub.withArgs('ListStacks', listParams, requestOption).resolves({
      'PageNumber': 1,
      'TotalCount': 3,
      'PageSize': 50,
      'Stacks': [
        {
          'StackId': stackId,
          'StackName': stackName
        }
      ]
    });

    requestStub.withArgs('CreateChangeSet', updateParams, requestOption).resolves({
      ChangeSetId: 'changeSetId'
    });

    requestStub.withArgs('GetStack', getStackParams).resolves({
      'Status': 'UPDATE_COMPLETE'
    });

    requestStub.withArgs('GetChangeSet', getChangeSetParam).resolves({
      'Status': 'COMPLETE',
      'Changes': changes
    });

    requestStub.withArgs('ExecuteChangeSet', execChangeSetParams, requestOption).resolves();

    const promptArguments = [{
      message: 'Please confirm to continue.',
      name: 'ok',
      type: 'confirm'
    }];

    requestStub.withArgs('ListStackEvents', listEventsParams, requestOption).resolves(listEventsResults);

    await deployByRos(stackName, tpl, false);

    assert.calledWith(requestStub.firstCall, 'ListStacks', listParams, requestOption);
    assert.calledWith(requestStub.secondCall, 'CreateChangeSet', updateParams, requestOption);
    assert.calledWith(requestStub.thirdCall, 'GetChangeSet', getChangeSetParam, requestOption);
    assert.calledWith(requestStub.lastCall, 'ListStackEvents', listEventsParams, requestOption);
    assert.calledWith(inquirer.prompt, promptArguments);
  });
});