'use strict';

module.exports = {
  FUN_NAS_SERVICE_PREFIX: '_FUN_NAS_',
  FUN_NAS_FUNCTION: 'fun-nas-function',
  FUN_NAS_TIMEOUT: 600 * 1000,
  FUN_NAS_UPLOAD_PARALLEL_COUNT: 5,
  FUN_NAS_FILE_COUNT_PER_REQUEST: 248,
  FUN_NAS_CHUNK_SIZE: 5 * 1024 * 1024
};